import agentTypes from "./commands/agent/types.ts";
import agentList from "./commands/agent/list.ts";
import agentRun from "./commands/agent/run.ts";
import agentShutdown from "./commands/agent/shutdown.ts";
import cost from "./commands/cost.ts";
import debugAppShutdown from "./commands/debug/app.ts";
import debugChat from "./commands/debug/chat.ts";
import debugLogging from "./commands/debug/logging.ts";
import debugMarkdown from "./commands/debug/markdown.ts";
import debugQuestions from "./commands/debug/questions.ts";
import debugServices from "./commands/debug/services.ts";
import help from "./commands/help.ts";
import hooksDisable from "./commands/hooks/disable.ts";
import hooksEnable from "./commands/hooks/enable.ts";
import hooksGet from "./commands/hooks/get.ts";
import hooksList from "./commands/hooks/list.ts";
import hooksReset from "./commands/hooks/reset.ts";
import hooksSelect from "./commands/hooks/select.ts";
import hooksSet from "./commands/hooks/set.ts";
import reset from "./commands/reset.ts";
import settings from "./commands/settings.ts";
import work from "./commands/work.ts";
import type {TokenRingAgentCommand} from "./types.ts";

export default [reset, hooksGet, hooksSet, hooksSelect, hooksList, hooksEnable, hooksDisable, hooksReset, settings, work, help, cost, agentTypes, agentList, agentRun, agentShutdown, debugAppShutdown, debugChat, debugLogging, debugMarkdown, debugQuestions, debugServices] satisfies TokenRingAgentCommand[];